import type { Product } from '@/lib/products/types';

export const sampleProducts: Product[] = [
  {
    id: '664f1f0db2d1d6f0a4d93a01',
    name: 'Pure Silk Kanjeevaram Saree',
    slug: 'pure-silk-kanjeevaram-saree',
    company: 'SHARNAYA Creations',
    category: 'Saree',
    audience: 'women',
    fabricType: 'Woven silk',
    colors: ['Maroon', 'Gold'],
    materials: ['Pure silk', 'Zari'],
    price: 18500,
    mrp: 28000,
    priceRange: '₹18,500',
    rating: 4.6,
    reviewCount: 128,
    bestseller: true,
    modelNote: 'Our model wears a Size S',
    images: ['/bb1.webp', '/bb2.webp', '/bb3.webp'],
    certifications: ['Silk Mark'],
    tags: ['premium', 'wedding', 'silk'],
    seoKeywords: ['kanjeevaram saree', 'silk saree', 'wedding saree'],
    imageFilename: 'public/bb1.webp',
    designer: 'SHARNAYA Creations',
    status: { active: true, featured: true },
    createdAt: '2024-11-12',
    updatedAt: '2025-05-20',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a02',
    name: 'Kanchipuram Temple Border Saree',
    slug: 'kanchipuram-temple-border-saree',
    company: 'Heritage Collection',
    category: 'Saree',
    audience: 'women',
    fabricType: 'Woven silk',
    colors: ['Green', 'Red', 'Gold'],
    materials: ['Pure silk', 'Temple zari'],
    price: 21000,
    mrp: 32000,
    priceRange: '₹21,000',
    rating: 4.4,
    reviewCount: 86,
    bestseller: true,
    certifications: ['Silk Mark', 'Handloom'],
    tags: ['temple', 'festive', 'heritage'],
    seoKeywords: ['kanchipuram saree', 'temple border saree'],
    images: ['/bb3.webp'],
    imageFilename: 'public/bb3.webp',
    designer: 'Heritage Collection',
    status: { active: true, featured: true },
    createdAt: '2024-10-05',
    updatedAt: '2025-04-18',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a03',
    name: 'Traditional Gold Border Saree',
    slug: 'traditional-gold-border-saree',
    company: 'SHARNAYA Creations',
    category: 'Saree',
    audience: 'women',
    fabricType: 'Woven silk',
    colors: ['Ivory', 'Gold'],
    materials: ['Silk', 'Zari'],
    price: 16500,
    mrp: 24000,
    priceRange: '₹16,500',
    rating: 4.2,
    reviewCount: 54,
    certifications: ['Silk Mark'],
    tags: ['classic', 'gold-border'],
    seoKeywords: ['gold border saree', 'traditional saree'],
    images: ['/bb2.webp'],
    imageFilename: 'public/bb2.webp',
    designer: 'SHARNAYA Creations',
    status: { active: true, featured: false },
    createdAt: '2025-01-08',
    updatedAt: '2025-05-02',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a04',
    name: 'Silk Veshti & Angavastram Set',
    slug: 'silk-veshti-angavastram-set',
    company: 'SHARNAYA Creations',
    category: 'Traditional menswear',
    audience: 'men',
    fabricType: 'Woven silk',
    colors: ['Cream', 'Gold'],
    materials: ['Pure silk'],
    price: 12500,
    priceRange: '₹12,500',
    certifications: ['Silk Mark'],
    tags: ['wedding', 'festive', 'veshti'],
    seoKeywords: ['silk veshti', 'angavastram set', 'mens traditional'],
    images: ['/images/products/men-veshti.jpg'],
    imageFilename: 'public/images/products/men-veshti.jpg',
    designer: 'SHARNAYA Creations',
    status: { active: true, featured: true },
    createdAt: '2025-02-14',
    updatedAt: '2025-05-28',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a05',
    name: 'Jacquard Silk Kurta Set',
    slug: 'jacquard-silk-kurta-set',
    company: 'Heritage Collection',
    category: 'Kurta set',
    audience: 'men',
    fabricType: 'Jacquard',
    colors: ['Navy', 'Gold'],
    materials: ['Silk blend'],
    price: 9800,
    priceRange: '₹9,800',
    certifications: [],
    tags: ['festive', 'kurta'],
    seoKeywords: ['silk kurta', 'mens ethnic wear'],
    images: ['/images/products/men-kurta.jpg'],
    imageFilename: 'public/images/products/men-kurta.jpg',
    designer: 'Heritage Collection',
    status: { active: true, featured: false },
    createdAt: '2025-03-01',
    updatedAt: '2025-05-15',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a06',
    name: 'Mustard Cotton Pavadai Set',
    slug: 'mustard-cotton-pavadai-set',
    company: 'Heritage Collection',
    category: 'Pavadai set',
    audience: 'children',
    fabricType: 'Woven cotton',
    colors: ['Mustard', 'Maroon'],
    materials: ['Cotton', 'Zari accents'],
    price: 8500,
    mrp: 12999,
    priceRange: '₹8,500',
    rating: 4.1,
    reviewCount: 286,
    bestseller: true,
    modelNote: 'Our model wears a Size S',
    certifications: [],
    tags: ['kids', 'festive', 'cotton'],
    seoKeywords: ['pattu pavadai kids', 'kids ethnic wear'],
    images: ['/bb4.webp'],
    imageFilename: 'public/bb4.webp',
    designer: 'Heritage Collection',
    status: { active: true, featured: true },
    createdAt: '2024-12-20',
    updatedAt: '2025-04-30',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a07',
    name: 'Kids Pattu Pavadai — Temple Motif',
    slug: 'kids-pattu-pavadai-temple',
    company: 'SHARNAYA Creations',
    category: 'Pavadai set',
    audience: 'children',
    fabricType: 'Silk',
    colors: ['Pink', 'Green', 'Gold'],
    materials: ['Silk', 'Zari'],
    price: 9200,
    priceRange: '₹9,200',
    certifications: ['Silk Mark'],
    tags: ['kids', 'silk', 'temple'],
    seoKeywords: ['kids pattu pavadai', 'silk pavadai'],
    images: ['/bb6.avif'],
    imageFilename: 'public/bb6.avif',
    designer: 'SHARNAYA Creations',
    status: { active: true, featured: false },
    createdAt: '2025-01-22',
    updatedAt: '2025-05-10',
  },
  {
    id: '664f1f0db2d1d6f0a4d93a08',
    name: 'Kids Festive Lehenga Set',
    slug: 'kids-festive-lehenga-set',
    company: 'SHARNAYA Creations',
    category: 'Lehenga set',
    audience: 'children',
    fabricType: 'Silk blend',
    colors: ['Red', 'Gold'],
    materials: ['Silk', 'Net'],
    price: 7500,
    priceRange: '₹7,500',
    certifications: [],
    tags: ['kids', 'lehenga', 'festive'],
    seoKeywords: ['kids lehenga', 'festive kids wear'],
    images: ['/bb5.avif'],
    imageFilename: 'public/bb5.avif',
    designer: 'SHARNAYA Creations',
    status: { active: true, featured: true },
    createdAt: '2025-02-08',
    updatedAt: '2025-06-01',
  },
];

export function getSampleProductById(id: string): Product | undefined {
  return sampleProducts.find(p => p.id === id);
}

export function getSampleProductBySlug(slug: string): Product | undefined {
  return sampleProducts.find(p => p.slug === slug);
}
